### ISSUE TITLE
How to get envoy environment variables in the Proxy-Wasm extension?

### ISSUE THREAD

**Issue by fzy-Line** [tetratelabs/proxy-wasm-go-sdk#102]
I need to get wordload instance information in proxy-wasm extension. I have tried to get these information through environment variables and reading files(such as /etc/istio/pod/labels) mounted by envoy, but all have failed. Can someone help me?

**Comment by mathetake** [comment]
- First of all, we need to put TinyGo's WASI target forward to support `os.Getenv` through WASI's `get_environ` interface.
- Proxy-Wasm spec is yet to have specification or consensus with regard to environment variables, and currently `proxy-wasm-cpp-host` leave it just "unimplemented" as you can see here https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/b7d3d13d75bb6b50f192252258bb9583bf723fa4/src/exports.cc#L769-L772

That said, we cannot read env variables from Wasm VM sides regardless of the languages we use.

I will file an issue in Proxy-Wasm's spec repository, and please stay tuned there. Thanks!

**Comment by fzy-Line** [comment]
@mathetake Thanks for you help. I will stay tuned there.

**Comment by mathetake** [comment]
resolved in  https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/126 and https://github.com/envoyproxy/envoy/pull/15136
