### ISSUE TITLE
Proxy-Wasm extension out of memory

### ISSUE THREAD

**Issue by fzy-Line** [tetratelabs/proxy-wasm-go-sdk#108]
I found out of memory problems with wasm extension in the following two situations: 
1. Define a large structure and instantiate it in the wasm extension, and then run the wasm extension.
2. Use Apache Jmeter(5 Threads) to evaluate the performance of wasm extension.

So, I want to know how to set the maximum memory each VM can allocate? Can someone help me?

**Comment by mathetake** [comment]
@fzy-Line Could you please provide me the followings for detail ? 
- The version or commit hash of this SDK
- The extension's code
- The configuration yaml of Envoy
- The version of Envoy (Envoy or Istio/proxyv2) and it's commit hash

FWIW, https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/86 resolved some memory leak issue.

**Comment by mathetake** [comment]
BTW, there's no way to grow VM's maximum memory from user program side. The "grow" instruction should be inserted in in the compiled codes by compilers and developers shouldn't care about that.

**Comment by fzy-Line** [comment]
I found the cause of the OOM. It doesn't looks like an proxy-wasm extension problem, but a problem of my code implementation. In golang, the map will not release memory after deleting elements. In my extension's code, I use a global map to share context: 

```
var records map[uint32]*RequestInfo

func saveRequestInfo(key uint32, requestInfo *RequestInfo){
	mutex.Lock()
	defer mutex.Unlock()
	records[key] = requestInfo
}

func (ctx *httpHeaders) OnHttpRequestHeaders(numHeaders int, endOfStream bool) types.Action {

	requestInfo := new(RequestInfo)

	// Get info from http head and set to requestInfo
	// ......

	// put requestInfo to map
	saveRequestInfo(ctx.contextID, requestInfo)

	return types.ActionContinue
}


func (ctx *httpHeaders) OnHttpResponseHeaders(numHeaders int, endOfStream bool) types.Action {

	requestInfo := records[ctx.contextID]

	// use these info and send a httpcall
	// ......

	// delete map element
	delete(records, ctx.contextID)

	return types.ActionContinue
}
```

The reference: [https://github.com/golang/go/issues/20135](https://github.com/golang/go/issues/20135)

So I want to know if there is a better way to share context in Proxy-wasm extension.

**Comment by mathetake** [comment]
why not just embed the info to fields in your `httpHeaders` struct?
