### ISSUE TITLE
modify l4 buffer

### ISSUE THREAD

**Issue by jgunvalson** [tetratelabs/proxy-wasm-go-sdk#115]
I'm trying to modify the upstream data being sent back from a network filter and encountering a bad argument status from https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/a3effdf2b2972001c4aea1b86ad1a984b2c69735/proxywasm/rawhostcall/rawhostcall.go#L70

I thought perhaps https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/45 may have covered this case, but the implementations seem to be specific to l7 filters.

Is this currently supported and I'm just setting the wrong buffer type or is it currently not supported by the sdk, cpp-host, or wasi?

**Comment by MikeSchlosser16** [comment]
It also looks like the existing HTTP filter returns a bad argument status, using the following code: 
```
	b := []byte(`{ "another": "body" }`)

		err = proxywasm.SetHttpResponseBody(b)
		if err != nil {
			proxywasm.LogErrorf("failed to set response body: %v", err)
			return types.ActionContinue
		}
```
 
Logs
```
[2021-01-22 10:09:57.796][11408281][error][wasm] [external/envoy/source/extensions/common/wasm/context.cc:1177] wasm log: failed to set response body: error status returned by host: bad argument
```

**Comment by jgunvalson** [comment]
The bad argument call is returned by the copyFrom method in envoy's wasm code. I was able to follow the code and trigger the happy path by changing my argument of maxSize to be equal to the entire length of the buffer rather than the length of the data I wanted to insert.
