### ISSUE TITLE
SetHttpRequestBody Is bad argument

### ISSUE THREAD

**Issue by cookieY** [tetratelabs/proxy-wasm-go-sdk#117]
ENV:

envoy  version: 5c801b25cae04f06bf48248c90e87d623d7a6283/1.17.0/Modified/DEBUG/BoringSSL
tinygo v0.16.0.

Hi 

I refer to examples/http_body 

```
func (ctx *context) OnHttpRequestBody(bodySize int, endOfStream bool) types.Action {
	proxywasm.LogInfof("body size: %d", bodySize)
	if bodySize != 0 {
		initialBody, err := proxywasm.GetHttpRequestBody(0, bodySize)
		if err != nil {
			proxywasm.LogErrorf("failed to get request body: %v", err)
			return types.ActionContinue
		}
		proxywasm.LogInfof("initial request body: %s", string(initialBody))
		err = proxywasm.SetHttpRequestBody([]byte(`{"hello":"henry"}`))
		if err != nil {
			proxywasm.LogErrorf("failed to set request body: %v", err)
			return types.ActionContinue
		}
		proxywasm.LogInfof("on http request body finished")
	}

	return types.ActionContinue
}
```
envoy debug

```
[2021-02-03 16:20:45.965][1141921][info][wasm] [source/extensions/common/wasm/context.cc:1171] wasm log: body size: 5
[2021-02-03 16:20:45.965][1141921][info][wasm] [source/extensions/common/wasm/context.cc:1171] wasm log: initial request body: {"hello":"Alice"}
[2021-02-03 16:20:45.965][1141921][error][wasm] [source/extensions/common/wasm/context.cc:1177] wasm log: failed to set request body: error status returned by host: bad argument

```

but in the Test case everything is ok, So why  failed to set request body: error status returned by host: bad argument 

thanks

**Comment by FalkFiedler** [comment]
image: istio/proxyv2:1.8.2
GolangVersion:"go1.15.5"
I get the same response from the SetHttpResponseBody function.

```
b := []byte(mynewBody)
		err = SetHTTPResponseBody(b)
		if err != nil {
			proxywasm.LogErrorf("failed to set response body: %v", err)
			return types.ActionContinue
		}
```

**Comment by cookieY** [comment]
@FalkFiedler 
maybe that`s the reason https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/49ed20e895b728aae6b811950a2939ecbaf76f7c/include/proxy-wasm/context.h#L82-L86

**Comment by pwoelfle** [comment]
I got the same issue on Envoy v1.17.0. The root cause (at least for my problem) was found here: https://github.com/envoyproxy/envoy/blob/v1.17.0/source/extensions/common/wasm/context.cc#L122-L146

Envoy supports the following buffer manipulations:
* **prepend**: `start` and `length` needs to be zero 
* **append**: `start` needs to be greater or equal to the origin buffer size
* **replace**: `start` needs to be zero and `length` must be greater or equal to the origin buffer size <- here the whole buffer is drained and then the new data are set

The current Proxy WASM Go SDK [`SetHttpRequestBody`](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/v0.0.14/proxywasm/hostcall.go#L130) implementation assumes that the new body is always equal or greater than the origin body. If it is not the case the envoy returns a bad argument error.

According to this I tested the following successfully:

`body` is the data which should prepend, append or replace 
`bodySize` is the origin body size given by the `OnHttpRequestBody` hook.

```go
func PrependToHttpRequestBody(body []byte, bodySize int) (int, error) {
	var bufferData *byte
	if len(body) != 0 {
		bufferData = &body[0]
	}

	st := rawhostcall.ProxySetBufferBytes(types.BufferTypeHttpRequestBody, 0, 0, bufferData, len(body))
	if st != types.StatusOK {
		return -1, types.StatusToError(st)
	}
	return bodySize + len(body), nil
}

func AppendToHttpRequestBody(body []byte, bodySize int) (int, error) {
	var bufferData *byte
	if len(body) != 0 {
		bufferData = &body[0]
	}

	st := rawhostcall.ProxySetBufferBytes(types.BufferTypeHttpRequestBody, bodySize, 0, bufferData, len(body))
	if st != types.StatusOK {
		return -1, types.StatusToError(st)
	}
	return bodySize + len(body), nil
}

func ReplaceHttpRequestBody(body []byte, bodySize int) (int, error) {
	var bufferData *byte
	if len(body) != 0 {
		bufferData = &body[0]
	}

	st := rawhostcall.ProxySetBufferBytes(types.BufferTypeHttpRequestBody, 0, bodySize, bufferData, len(body))
	if st != types.StatusOK {
		return -1, types.StatusToError(st)
	}
	return len(body), nil
}
```

**Comment by djannot** [comment]
@pwoelfle do you have a working example with the body manipulation ?
I'm trying to implement a modification of the response body and I get some issues with the fact that I need to update the content-length and can't find a way to do it properly (using ActionPause, ...).

**Comment by pwoelfle** [comment]
@djannot I faced the same problem. It's not possible to adjust the Content-Length HTTP header instead you have to remove this header.

See also in the Rust SDK: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/v0.1.3/examples/http_body.rs#L48

**Comment by abhide** [comment]
@djannot You will have to remove Content-Length header from HTTP response headers.
Using wasm go sdk; check this: https://github.com/abhide/envoy-wasm-experiments/blob/main/main.go#L72
The issue happens on the http client side; where the only a part of the output (equal to Content-length) gets read and output looks truncated.

I haven't tried setting Content-Length to be equal to sum of original content-length + length introduced by changes from within the wasm filter.

**Comment by djannot** [comment]
@abhide that's what I've done at the end, because I wasn't able to update the value

**Comment by FrimIdan** [comment]
@pwoelfle So there is a limitation in Envoy and set buffer can't replace the current buffer with a shorter one?
Did you find/opened an issue in Envoy for it?

**Comment by pwoelfle** [comment]
@FrimIdan No there is no limitation in Envoy. The buffer can be replaced - even with a shorter length - but the `length` argument must be equal or greater than the current buffer size ([see here](https://github.com/envoyproxy/envoy/blob/v1.17.0/source/extensions/common/wasm/context.cc#L128)).

From my perspective, the Proxy WASM `SetHttpRequestBody` could be changed towards something similar which I posted above to fit the Envoy logic.

**Comment by mathetake** [comment]
Hi all, I implemented the API by @pwoelfle as in https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/117#issuecomment-789530828, and believe fixed this issue. 

Please take a look at this example https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/examples/http_body for detail. Thanks!
