### ISSUE TITLE
Missing proxy_get_buffer_status() and proxy_get_header_map_size()

### ISSUE THREAD

**Issue by esnible** [tetratelabs/proxy-wasm-go-sdk#118]
I'd like to see proxy_get_buffer_status(), e.g. https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/92f02c0001592199d99f946cea34637ff095a8ba/include/proxy-wasm/wasm_api_impl.h#L147

Also proxy_get_header_map_size() , e.g. https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/92f02c0001592199d99f946cea34637ff095a8ba/include/proxy-wasm/wasm_api_impl.h#L192

I use these when debugging new extensions.

**Comment by mathetake** [comment]
https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/451
