### ISSUE TITLE
How can the request query params be modified?

### ISSUE THREAD

**Issue by HasmitaA** [tetratelabs/proxy-wasm-go-sdk#126]
I see APIs for modifying the request/response headers and body, but none for modifying the request query params. Is this not supported?

**Comment by mathetake** [comment]
You can get the path (of course, which includes query params) and modify through GetHttpRequestHeader and SetHttpRequestHeader calls.

**Comment by HasmitaA** [comment]
How can we get the path, since we do not have access to the request object? Also how can SetHttpRequestHeader() API be used to modify the query params?

**Comment by mathetake** [comment]
See 
- https://greenbytes.de/tech/webdav/draft-ietf-httpbis-http2-09.html#HttpRequest
- https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/examples/access_logger/main.go#L37
