### ISSUE TITLE
Examples tests are not working

### ISSUE THREAD

**Issue by Zagidziran** [tetratelabs/proxy-wasm-go-sdk#140]
Hi, 

there is no recipe to run test in the make file. And it seems tests are not working at all.

I've created an issue on tinygo describing the symptom, as far I'm not sure what is the root cause

https://github.com/tinygo-org/tinygo/issues/1795#issue-857028374

**Comment by mathetake** [comment]
See https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/Makefile and it’s verified on CI

**Comment by mathetake** [comment]
Note that the test is NOTHING to do with TinyGo since it does use the official tool chain.
