### ISSUE TITLE
Clarification on error handling

### ISSUE THREAD

**Issue by dippynark** [tetratelabs/proxy-wasm-go-sdk#152]
The example auth module dispatches a HTTP request to determine whether to allow the request: https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/examples/http_auth_random/main.go#L61-L65

This logs a critical error and returns a continue action. Does this mean that if the auth service is down all requests will be allowed through? i.e. does this code fail open?

If so, how would you fail closed? You could use something like `proxywasm.SendHttpResponse(403...` but then how do you handle any error returned by that function?

**Comment by mathetake** [comment]
> does this code fail open?
hi @dippynark, that's a good question.  actually it does fail open.

As of now, Go SDK doesn't support host calls to close in case of failure (named `closeUpstream` and `closeDownStream`) yet. But it's easy to implement so will do in a week or so. Thanks!

**Comment by dippynark** [comment]
Awesome, thanks! I guess will leave this open until then? Happy to close it though as it answers the question

**Comment by mathetake** [comment]
yeah let's leave this open until then. Thanks!

**Comment by skirsten** [comment]
Hi,

I did not find any api in the [spec](https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT) that would support closing the connection for HTTP context.
The referenced `closeUpstream` and `closeDownStream` are supposedly only for TCP context.

> You could use something like proxywasm.SendHttpResponse(403... but then how do you handle any error returned by that function?

This is exactly what I need to know. Could we use `panic` in that case? I need to somehow make sure the request processing is aborted.

**Comment by skirsten** [comment]
Looking at the rust examples https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/master/examples/http_auth_random.rs and https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/master/examples/http_headers.rs it seems they just leave the processing paused or never resume it in the case there could be an error.
Does this mean that the request will forever stay open or is it smart enough to notice there are no remaining callbacks and abort the request?

**Comment by mathetake** [comment]
https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/451
