### ISSUE TITLE
SetDownstreamData/SetUpstreamData support

### ISSUE THREAD

**Issue by FrimIdan** [tetratelabs/proxy-wasm-go-sdk#153]
Do you think of adding support for SetDownstreamData/SetUpstreamData like in the C++ SDK (https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/master/proxy_wasm_api.h#L900)
Something like SetHttpRequestBody but for data?

**Comment by mathetake** [comment]
done in #156. Thx!
