### ISSUE TITLE
cgo problem

### ISSUE THREAD

**Issue by rtttech** [tetratelabs/proxy-wasm-go-sdk#180]
I used cgo in my code as following, compile success but wasm load failed: "Failed to load Wasm module due to a missing import: env.my_time"

/*
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

int64_t my_time() {
	return time(NULL);
}
*/
import "C"

...

**Comment by mathetake** [comment]
You should check "my_time" is actually implemented in your Wasm binary (e.g. by looking at its text format) and make sure that is not "imported" one. That error message says that your binary DOES NOT have it implemented and just imports it.

Anyway this is not a issue for this SDK, but rather your compilation issue in TinyGo. Closing.
