### ISSUE TITLE
handle upstream error

### ISSUE THREAD

**Issue by rtttech** [tetratelabs/proxy-wasm-go-sdk#181]
How to capture and handle upstream error in wasm , for example, upstream connect failed.

**Comment by mathetake** [comment]
could you elaborate on what exactly you mean by "handle"? All you can do is operating on [these events](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/proxywasm/context.go#L34-L51) as specified in Proxy-Wasm specification. You won't be able to do beyond that. 

Closing until a further question specific to this SDK arises.

**Comment by rtttech** [comment]
If upstream connection failed, which event will be triggered?
