### ISSUE TITLE
Add Labels to exposed metrics (Question)

### ISSUE THREAD

**Issue by fbalicchia** [tetratelabs/proxy-wasm-go-sdk#223]
Hi,
I'd like to know if possible to add labels to metrics exposed with `go-sdk.` At the moment of writing, I saw that is possible to add only the key but probably I'm misunderstanding something.
Thanks for help

**Comment by fbalicchia** [comment]
Ops sorry just see this issue https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/issues/130

**Comment by mathetake** [comment]
Hi @fbalicchia, "tags" are not directly supported in the Wasm ABI and there's several reasons for this (one is Envoy's internal API doesn't support dynamic tags). That means this is not the Go SDK specific issue, and you cannot define tags with any language SDK.

However you can "extract" tags from the name of metrics by configuring Envoy's StatsConfig.stats_tags(https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#config-metrics-v3-statsconfig) properly. This is exactly what Istio does where the expose prometheus metrics with their custom tags.

**Comment by fbalicchia** [comment]
thanks, @mathetake for explanation

**Comment by mathetake** [comment]
I hope this https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/246 clarify your question!

**Comment by fbalicchia** [comment]
@mathetake yes thanks
