### ISSUE TITLE
Make SetEffectiveContext public

### ISSUE THREAD

**Issue by ikeeip** [tetratelabs/proxy-wasm-go-sdk#228]
## Describe the bug / error

To resume HTTP requests from OnTick callback we need set effective context properly, but currently it can't be done. I suggest to make public SetEffectiveContext func.

## What is your Envoy/Istio version?
```
$ envoy --version
envoy  version: 96701cb24611b0f3aac1cc0dd8bf8589fbdf8e9e/1.20.0/Clean/RELEASE/BoringSSL
```

## What is the SDK version?
```
v0.15.0 and dev
```

## What is your TinyGo version?
```
$ tinygo version
tinygo version 0.21.0 linux/amd64 (using go version go1.17 and LLVM version 11.0.0)
```

## URL or snippet of your code including Envoy configuration

The `envoy.log`, `envoy.yaml`, `main.go` located here: https://gist.github.com/ikeeip/4e6914bcc4e9efa0e4155c8a70029e0d

```sh
$ curl http://0.0.0.0:18000 -v --max-time 10
*   Trying 0.0.0.0:18000...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 18000 (#0)
> GET / HTTP/1.1
> Host: 0.0.0.0:18000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Operation timed out after 10001 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 10001 milliseconds with 0 bytes received
```

**Comment by mathetake** [comment]
> To resume HTTP requests from OnTick callback we need set effective context properly, but currently it can't be done. I suggest to make public SetEffectiveContext func.

Thanks @ikeeip, this makes sense, and I approve this proposal! Do you want to do a PR by yourself?
