### ISSUE TITLE
Is it production ready?

### ISSUE THREAD

**Issue by ktalg** [tetratelabs/proxy-wasm-go-sdk#232]
Should I use this in a production environment or only for test until now(2021.12)?

**Comment by mathetake** [comment]
It depends on how you define "production ready". Given the fact that several companies out there have already started using this SDK in production, maybe we could say this is production ready.

But on the other hand, Wasm extension is still in alpha and kind of experimental phase [as you can see in the envoy repo](https://github.com/envoyproxy/envoy/blob/main/source/extensions/extensions_metadata.yaml#L276-L280), which is not limited to this Go SDK, but also applies to all the other languages.

**Comment by ktalg** [comment]
Thanks for your hard work and answer!

**Comment by Brunomachadob** [comment]
So I guess we could say if it covers our current use cases and things work fine on our unit and integration tests, it should be safe in regards to runtime execution?

I would be willing to try it to replace some authentication, decorators and etc we have using Lua Scripts.
Plus the ability of pushing metrics, something we don't have on Lua.

If I understood right, the main concern here would be breaking changes on the API/SDK.

Thanks!

**Comment by mathetake** [comment]
Note: API is unstable, but several companies are already using this SDK in production. eg https://www.youtube.com/watch?v=2CKHXhypCXs
