### ISSUE TITLE
i can't get response when is use helloworld.wasm

### ISSUE THREAD

**Issue by wanghonglei5181** [tetratelabs/proxy-wasm-go-sdk#233]
## Describe the bug / error
can‘t get the response ,when use the helloworld.wasm
## how to run envoy in my test
./envoy -c envoy.yaml

root@nvm-8vcpu-16gb-dbl-m85dhmt:/data1/workspace/src/github.com/tetratelabs/proxy-wasm-go-sdk-main# tree 
.
├── doc
│   ├── CONTRIBUTING.md
│   ├── images
│   │   ├── shared_data.png
│   │   ├── shared_queue.png
│   │   └── terminology.png
│   └── OVERVIEW.md
├── e2e
│   ├── e2e_test.go
│   └── main_test.go
├── envoy
├── envoy.yaml
├── examples
│   ├── dispatch_call_on_tick
│   │   ├── envoy.yaml
│   │   ├── main.go
│   │   ├── main.go.wasm
│   │   ├── main_test.go
│   │   └── README.md
│   ├── foreign_call_on_tick
│   │   ├── envoy.yaml
│   │   ├── main.go
│   │   ├── main.go.wasm
│   │   ├── main_test.go
│   │   └── README.md
│   ├── helloworld
│   │   ├── envoy.yaml
│   │   ├── main.go
│   │   ├── main.go.wasm
│   │   ├── main_test.go
│   │   └── README.md
## What is your Envoy/Istio version?
envoy:1.20.1
os:ubuntu 20.04
## What is the SDK version?
master branch
## What is your TinyGo version?
0.21.0
## URL or snippet of your code including Envoy configuration
/data1/workspace/src/github.com/tetratelabs/proxy-wasm-go-sdk-main/examples/helloworld/envoy.yaml
## Additional context (Optional)
the envoy output

[2021-12-27 07:25:04.379][602402][info][wasm] [source/extensions/common/wasm/context.cc:1167] wasm log: panic: invalid context id on proxy_on_context_create
[2021-12-27 07:25:04.379][602402][error][wasm] [source/extensions/common/wasm/wasm_vm.cc:38] Function: proxy_on_context_create failed: Uncaught RuntimeError: unreachable
Proxy-Wasm plugin in-VM backtrace:
  0:  0xd40 - runtime._panic
  1:  0xf7ee - proxy_on_context_create
[2021-12-27 07:25:04.701][602379][info][wasm] [source/extensions/common/wasm/context.cc:1167] wasm log: It's 1640589904701764000: random value: 16799284681896691881
[2021-12-27 07:25:04.701][602379][info][wasm] [source/extensions/common/wasm/context.cc:1167] wasm log: OnTick called

**Comment by mathetake** [comment]
Thanks, #236 resolved this, though please note that helloworld example is not intended to make Http requests against it. See https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/examples/helloworld/README.md

**Comment by wanghonglei5181** [comment]
thanks!
