### ISSUE TITLE
Support for writing for WASM for UDP

### ISSUE THREAD

**Issue by srikarrao** [tetratelabs/proxy-wasm-go-sdk#244]
Hey, new to WASMs for envoy proxy, and while trying the examples I see the support for HTTP & TCP but there is no UDP protocol support. I want to check if this is something the SDK will support in the future? Thank you. 

https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/proxywasm/types/context.go

**Comment by mathetake** [comment]
UDP is not supported by Proxy-Wasm now, so could you open an issue on [proxy-wasm/spec](https://github.com/proxy-wasm/spec)? Thanks!

**Comment by srikarrao** [comment]
I will do that. Thanks @mathetake
