### ISSUE TITLE
test framework: Implement ProxyGetProperty and ProxySetProperty

### ISSUE THREAD

**Issue by jmjolysc** [tetratelabs/proxy-wasm-go-sdk#250]
Hello there,

Currently, the `ProxyGetProperty` and `ProxySetProperty` methods are not implemented in `proxytest`. This prevents developers from writing more complete unit tests. Would you consider the implementation of those methods as a feature improvement?

When looking at the code, one approach could be adding a map (maybe `string` or `[]byte` to `[]byte`) in the `hostEmulator` data structure of the `proxytest` package, in order to store the state of properties. If you also think that's a straightforward approach, would you like me to give it a try and submit a pull request?

Thank you.

**Comment by mathetake** [comment]
sg! I would appreciate it if you could give it a shot. Thanks!
