### ISSUE TITLE
Wasm golang filter - error when using time.Sleep function

### ISSUE THREAD

**Issue by rodrigovc** [tetratelabs/proxy-wasm-go-sdk#251]
Hello, how are you doing? I have been working on as wasm filter written in golang and I had  the following error when I used the time go package for a time.Sleep function.
```
{"level":"error","time":"2022-02-18T14:43:27.719183Z","scope":"envoy wasm","msg":"Failed to load Wasm module due to a missing import: wasi_snapshot_preview1.poll_oneoff"}
{"level":"error","time":"2022-02-18T14:43:27.719220Z","scope":"envoy wasm","msg":"Wasm VM failed Failed to initialize Wasm code"}
{"level":"debug","time":"2022-02-18T14:43:27.719225Z","scope":"envoy wasm","msg":"~Wasm 28 remaining active"}
{"level":"trace","time":"2022-02-18T14:43:27.720989Z","scope":"envoy wasm","msg":"Unable to create Wasm"}
{"level":"critical","time":"2022-02-18T14:43:27.721043Z","scope":"envoy wasm","msg":"Plugin configured to fail closed failed to load"}
{"level":"critical","time":"2022-02-18T14:43:27.721058Z","scope":"envoy wasm","msg":"Plugin configured to fail closed failed to load"}
{"level":"critical","time":"2022-02-18T14:43:27.721083Z","scope":"envoy wasm","msg":"Plugin configured to fail closed failed to load"}
```

Here is the line in goland that is giving the problem (I took it out of the code for simplicity, if I remove the delay from the code it works as is):
```
import (
	"time"
)				
time.Sleep(300 * time.Millisecond)
```

I am actually translating a previous lua envoy filter that we had to a wasm filter, and I was able to implemente delays on the lua filter. We are using this for a retry strategy. Do any of you guys knows why the time package is failing when loaded into envoy (I did check that this package is supported by TinyGo)? If it can’t be loaded is there any other way of getting a small delay on the wasm code?

**Comment by mathetake** [comment]
Sleep cannot be used on Envoy due to its async mechanism and threading model, and you will never be able to use sleep or concurrency stuff. 

Instead, you could combine OnTick and StopIteration to achieve the delay: This is the example exactly doing the same thing you are trying to achieve: https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/examples/postpone_requests

**Comment by rodrigovc** [comment]
Thank you
