### ISSUE TITLE
dispatchHttpCall 

### ISSUE THREAD

**Issue by pjjwpc** [tetratelabs/proxy-wasm-go-sdk#252]
## Describe the bug / error
```
ctx.callBack = func(number, bodySize, numTrailers int) {
		rspBody, err := proxywasm.GetHttpCallResponseBody(0, 50000)
		if err != nil {
			proxywasm.LogCriticalf("GetToken erro:%v", err)
		}

		jsonarray := gjson.GetManyBytes(rspBody, "access_token", "expires_in", "token_type", "scope")
		ctx.token = jsonarray[0].String()

		proxywasm.LogInfof("callBack token:%s", ctx.token)
	}

	formdata := strings.Join(jwtParams, "&")

	if _, err := proxywasm.DispatchHttpCall("auth", headers, str2bytes(formdata), nil, 1000, ctx.callBack); err != nil {
		proxywasm.LogCriticalf("Get Token err :%v", err)
	}
	proxywasm.LogInfof("set req header :%s", ctx.token)
	proxywasm.ReplaceHttpRequestHeader("access_token-2", ctx.token)
	return types.ActionContinue
```
ctx.token value is empty
## What is your Envoy/Istio version?
envoy 1.20.1
## What is the SDK version?
0.16
## What is your TinyGo version?
tinygo 0.22.0
## URL or snippet of your code including Envoy configuration
```
- name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              config:
                name: "test"
                root_id: "test"
                configuration:
                  '@type': type.googleapis.com/google.protobuf.StringValue
                  value: |
                    {
                      "name": "test",
                      "age": 123
                    }
                vm_config:
                  runtime: "envoy.wasm.runtime.v8"
                  configuration:
                    '@type': type.googleapis.com/google.protobuf.StringValue
                    value: |
                      {
                          "grantType":"abc",
                          "clientId":"bcd",
                          "clientSecret":"cde",
                          "scope":"adsfdfad asdfadsf"
                      }
                  code:
                    local:
                      filename: './jwt.wasm'
```

**Comment by mathetake** [comment]
Could you describe what’s not expected what’s you want solve clearly? I have no idea what’s the problem here from the single comment “token is empty”, and I don’t see this is our SDK issue

**Comment by pjjwpc** [comment]
How do I get the result of the external request from the DispatchHttpCall method and add the result to the current request?
For example, I call the external authentication system, get the token, and add the token to the current request header.

**Comment by mathetake** [comment]
https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/proxywasm/hostcall.go#L100-L101 could you read the godoc before asking questions?

**Comment by pjjwpc** [comment]
How do I get the result of the external request from the DispatchHttpCall method and add the result to the current request?
For example, I call the external authentication system, get the token, and add the token to the current request header.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Takeshi ***@***.***&gt;; 
发送时间: 2022年2月22日(星期二) 上午10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tetratelabs/proxy-wasm-go-sdk] Cannot properly implement JWT validation  (Issue #252)






https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/proxywasm/hostcall.go# L100 - L101你能在问问题前读一下戈多克吗？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或机器人. 
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.***与&gt;

**Comment by jamesmulcahy** [comment]
@pjjwpc Execution resumes in your callback, so you make calls like `proxywasm.AddHttpRequestHeader` with the content you want to add to headers, and then call `proxywasm.ResumeHttpRequest`.
