### ISSUE TITLE
Envoy loads incorrect binaries when multiple filters are configured using a RemoteDataSource

### ISSUE THREAD

**Issue by mattjnewberry** [tetratelabs/proxy-wasm-go-sdk#262]
## Describe the bug / error
When configuring envoy with multiple typed configs using a [config.core.v3.RemoteDataSource](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-remotedatasource). On startup, both envoy filters are fetched remotely but only only the first fetched binary is running on envoy (and is running twice).

## What is your Envoy/Istio version?
1.19.1

## What is the SDK version?
0.16.0

## What is your TinyGo version?
0.20.0

## URL or snippet of your code including Envoy configuration
https://github.com/mattjnewberry/proxy-wasm-go-sdk/tree/main/examples/cached_filters_bug_repro

## Additional context (Optional)

You can see in the repro that both filters have different sha256 checksums, and have different config specified. After startup, each filter is loaded with the distinct config, but the actual binary is the same:

```
wasm log: Filter 1 OnTick: config: Filter 2, guid: 5143901740323388853, time: 1643798659843180000
wasm log: Filter 1 OnTick: config: Filter 1, guid: 6567645268386784623, time: 1643798659843212000
```

**Comment by mathetake** [comment]
could you open the issue in envoy repo?  I don't think this is the SDK issue at all. Thanks!

**Comment by mattjnewberry** [comment]
Yeah, will do, thanks. I agree, only raised it here to begin with to follow the dependency chain. I'll link the issue when I get round to raising it 👍
