### ISSUE TITLE
Where can I find the hostcall implementation?

### ISSUE THREAD

**Issue by ktalg** [tetratelabs/proxy-wasm-go-sdk#274]
It seems that all hostcall will go into proxywasm/internal/abi_*.go but it's just some superficial,is there any doc talking about the implementation ?Thanks.

https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/a7d6d12c008aeb9e0a59fab545d2625569e3319a/proxywasm/internal/abi_hostcalls.go#L19-L20

**Comment by mathetake** [comment]
See https://github.com/proxy-wasm/spec
