### ISSUE TITLE
Shared queue access/thread safety

### ISSUE THREAD

**Issue by anups4** [tetratelabs/proxy-wasm-go-sdk#275]
I am pretty new to Envoy/Wasm and looking into leveraging https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/examples/shared_queue. It seems sender and receiver don't need to provide thread safety mechanism even when running into multiple worker threads and that leads me to believe thread safe access to queue is handled by host/proxy ABI implementation. Can you please help me understand how it works and point me to code where thread safety is taken care of?

**Comment by mathetake** [comment]
https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/master/src/shared_queue.cc#L109 this is the host implementation code where the host ensures the thread safety.
