### ISSUE TITLE
how to share data between inbound wasm and outbound wasm

### ISSUE THREAD

**Issue by 13567436138** [tetratelabs/proxy-wasm-go-sdk#294]
## Describe the bug / error
how to share data between inbound wasm and outbound wasm
I want get request headers when it is inbound，and set the same request headers when outbound？
any code will be thankful。
## What is your Envoy/Istio version?
1.13.3

**Comment by mathetake** [comment]
Use shared_data, but you have to add identifier to associate outbounds with specific inbounds, but yeah they are out of scope of this repo.
