### ISSUE TITLE
DispatchHttpCall need to copy  upstream response from envoy to wasm machine ?

### ISSUE THREAD

**Issue by Neil-Boyle** [tetratelabs/proxy-wasm-go-sdk#297]
## Describe 
DispatchHttpCall need to copy  upstream response from envoy to wasm machine ?

in wasm plugin, we need to dispatch a request to different cluster/ router, base on request header , with DispatchHttpCall function.

it seems GetHttpRequestBody(start, maxSize int) function is requested. otherwise upstream response is missed.

question:

is the copy of upstream response is inevitable ?  any other impl available?

any help will be welcome , thk

proxywasm.DispatchHttpCall("test-cluster", header, unavoidableBody, nil, 5000, callback)

```
// GetHttpRequestBody is used for retrieving the entire http request body.
// Only available during types.HttpContext.OnHttpRequestBody.
func GetHttpRequestBody(start, maxSize int) ([]byte, error) {}

```

```
// DispatchHttpCall is for dipatching http calls to a remote cluster. This can be used by all contexts
// including Tcp and Root contexts. "cluster" arg specifies the remote cluster the host will send
// the request against with "headers", "body", "trailers" arguments. If the host successfully made the request
// and recevived the response from the remote cluster, then "callBack" function is called.
// During callBack is called, "GetHttpCallResponseHeaders", "GetHttpCallResponseBody", "GetHttpCallResponseTrailers"
// calls are available for accessing the response information.
func DispatchHttpCall(
	cluster string,
	headers [][2]string,
	body []byte,
	trailers [][2]string,
	timeoutMillisecond uint32,
	callBack func(numHeaders, bodySize, numTrailers int),
) (calloutID uint32, err error) {}
```

## What is the SDK version?
github.com/tetratelabs/proxy-wasm-go-sdk v0.16.1-0.20220112233158-3275d6a8ac38

**Comment by mathetake** [comment]
I don't get what's your question is, but basically impossible by design.
