### ISSUE TITLE
Better practice for multiple DispatchHttpCall

### ISSUE THREAD

**Issue by MengjiaLiang** [tetratelabs/proxy-wasm-go-sdk#304]
Hi there,

I am trying to migrate our Lua-based EnvoyFilter to be proxy-wasm-based EnvoyFilter.

I am now facing an issue related to the callback model for DispatchHttpCall, hence, wondering if any experts can share with some better practices.

Originally, our Lua script will do
```
1.   HTTPCall to service A
2.  Populate headers based on the response from A
3.  Another HTTPCall to service B
4.  Populate headers based on the response from B
```
This workflow can be run sequentially in a single Lua script.

When it comes to the proxy-wasm world, I found this pattern is not working
```
func (ctx *HttpContext) OnHttpRequestHeaders(int, bool) types.Action {
	if _, err := proxywasm.DispatchHttpCall(
		LocationServiceHost,
		headers,
		nil,
		nil,
		DefaultHTTPCallTimeout,
		createGetLocationCallBack(ctx),
	); err != nil {
		proxywasm.LogCriticalf("dispatch httpcall %s failed: %v", path, err)
		return err
	}
       
       // some operations to get the values from context and set header.

       return types.ActionContinue
}
```
I checked the examples in this repository,
seems the `OnHttpRequestHeaders` should return `types.ActionPause` instead, and the operations to set headers should be moved into the call back function.

One thing I am curious about here,
is there a way that we can dispatch multiple HTTP calls inside `OnHttpRequestHeaders`?

If I take multiple HTTP calls here, is that possible to synchronize the callback functions to resume the request when all the callback functions are finished?  

Looking forward to any thoughts from experts. Appreciate that in advance！

**Comment by mathetake** [comment]
yeah can continue the request from the dispatched call by calling `ResumeHttpRequest` inside the dispatched callback (I think I should've documented it here) https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/bc850cd5e90fe2984b12e025e2614dba37ac46ff/proxywasm/hostcall.go#L348-L352

**Comment by mathetake** [comment]
as for the multiple callback synchronization, you can use `contextID` to track the status in your code (note that Proxy-Wasm's Wasm is single-threaded so you don't need to care about the locks etc.)

**Comment by mathetake** [comment]
this example https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/084c08a2561445e14663070f69970cb702d678d1/examples/postpone_requests might be of your interest

**Comment by mathetake** [comment]
ok let me add an example for your use case as this seems kinda complex

**Comment by mathetake** [comment]
there you go https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/305

**Comment by MengjiaLiang** [comment]
@mathetake  Appreciate your help! The new example is awesome, thanks for adding it!
