### ISSUE TITLE
Ability to print timings for ABI invocations

### ISSUE THREAD

**Issue by anuraaga** [tetratelabs/proxy-wasm-go-sdk#326]
We are doing performance investigation of a proxy-wasm filter and as a first step implemented printing of invocation times within our plugin. We'd like to be able to get times that are as close to host vs guest as possible so were wondering whether it would be reasonable to add a build tag that would enable printing of ABI invocations.

Something like this with build tag `proxywasm-print-timing`

https://github.com/anuraaga/coraza-wasm-filter/pull/33/files#diff-3f1e96d7c9683d59c31db68779706defb5c12792346f0379a04cecc4a463246f

and add to each abi function callback, e.g.

```go
//export proxy_on_new_connection
func proxyOnNewConnection(contextID uint32) types.Action {
        defer logTiming("proxyOnNewConnection", time.Now())
	ctx, ok := currentState.tcpContexts[contextID]
	if !ok {
		panic("invalid context")
	}
	currentState.setActiveContextID(contextID)
	return ctx.OnNewConnection()
}
```

**Comment by anuraaga** [comment]
Perhaps `time.Now()` should be a `currentTime()` function that is also stubbed to avoid calling into the host for current time when tag is disabled.

**Comment by mathetake** [comment]
I would suggest define the flag constant `const printTiming = true/false` and guard the entire defer statement

```
if printTiming { defer logTiming("proxyOnNewConnection", time.Now()) }
```

so that we can remove the entire defer statement for sure by the compiler.

**Comment by anuraaga** [comment]
Thanks @mathetake makes sense
