### ISSUE TITLE
Question: Why proxy-wasm-go-sdk treats empty buffer different from proxy-wasm-rust-sdk

### ISSUE THREAD

**Issue by spacewander** [tetratelabs/proxy-wasm-go-sdk#330]
In the Go SDK, an empty buffer is considered an error (ErrorStatusNotFound):
https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/132ee0a06ac20082b3c172e251ec8c48aeaa4531/proxywasm/hostcall.go#L849-L852

However, the Rust SDK considers it as `Ok(None)`:
https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/1541f62eb83dabcb16d35bb3c6e4bf64d8bc8d2a/src/hostcalls.rs#L100

What's the reason behind the different choices?

**Comment by mathetake** [comment]
It’s not a semantically diff but just how you handle. We don’t need to align that with Rust (no reason for that), and you can handle with`errors.Is`
