### ISSUE TITLE
Question: Debugging methods

### ISSUE THREAD

**Issue by RoeiGanor** [tetratelabs/proxy-wasm-go-sdk#334]
Im developing a plugin for envoy and i wonder what is the best method to debug this program with breakpoints and looking into the memory.
 I didn't find any good method and i'm currently working blind and i hope you can share from your experience what is the best method to develop such plugin.

**Comment by mathetake** [comment]
https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/451
