### ISSUE TITLE
Replace GC implementation with bdwgc

### ISSUE THREAD

**Issue by johnlanni** [tetratelabs/proxy-wasm-go-sdk#344]
Corazawaf uses bdwgc to replace tinygo's built-in gc, which works well:
https://github.com/corazawaf/coraza-proxy-wasm/pull/73

Maybe it can be used as a default gc mechanism for proxy-wasm-go-sdk.

**Comment by mathetake** [comment]
No, I don't think I would make it default and users are already feee to choose it
