### ISSUE TITLE
Log functions with maps can call functions unimplemented in tinygo

### ISSUE THREAD

**Issue by while1malloc0** [tetratelabs/proxy-wasm-go-sdk#350]
## Describe the bug / error

The various `proxywasm.Log*f` functions [make a call to `fmt.Sprintf`](https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/proxywasm/hostcall.go#L655) in order to format the message before passing it on to the `internal.ProxyLog` function. In most cases this is harmless, but in special cases such as using `%v` with a `map`, [reflect.MapRange is called as part of formatting the output](https://cs.opensource.google/go/go/+/refs/tags/go1.19.4:src/internal/fmtsort/sort.go;l=61). This function is unimplemented in TinyGo and causes a panic.

## What is your Envoy/Istio version?

envoy  version: 0de60452be1fa329c16076916b6bfe1f672aeed4/1.17.4/Clean/RELEASE/BoringSSL

## What is the SDK version?

v0.20.0

## What is your TinyGo version?

tinygo version 0.26.0 darwin/amd64 (using go version go1.18 and LLVM version 14.0.0)

## URL or snippet of your code including Envoy configuration

NB: I've omitted the Envoy config since this is a lib/tinygo issue, but I'm happy to include a minimal one if that makes repro easier.

```go
package main

import (
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
)

type vmContext struct {
	types.DefaultVMContext
}

func (*vmContext) NewPluginContext(contextID uint32) types.PluginContext {
	proxywasm.LogInfof("%v", map[string]string{}) // this line will panic
	return types.DefaultPluginContext
}

func main() {
	proxywasm.LogInfo("starting wasm filter")
	proxywasm.SetVMContext(&vmContext{})
}
```

## Additional context (Optional)

The call stack for calling `reflect.MapRange` is (I think, the code is pretty verbose):

- [Sprintf](https://cs.opensource.google/go/go/+/master:src/fmt/print.go;l=237;drc=f721fa3be9bb52524f97b409606f9423437535e8?q=Sprintf&sq=&ss=go%2Fgo)
- [pp.doPrint](https://cs.opensource.google/go/go/+/master:src/fmt/print.go;drc=f721fa3be9bb52524f97b409606f9423437535e8;l=1021)
- [pp.printArg](https://cs.opensource.google/go/go/+/master:src/fmt/print.go;drc=f721fa3be9bb52524f97b409606f9423437535e8;l=681)
- [pp.printValue](https://cs.opensource.google/go/go/+/master:src/fmt/print.go;drc=f721fa3be9bb52524f97b409606f9423437535e8;l=766)
- [fmtsort.Sort](https://cs.opensource.google/go/go/+/master:src/internal/fmtsort/sort.go;drc=f721fa3be9bb52524f97b409606f9423437535e8;l=51)

I understand that this might not be an issue with `proxywasm` per se, but since `proxywasm` defines its own logging wrappers this felt like a reasonable place to raise the issue. The way I see it, there's a few potential solutions here:

- Check the formatting verb and do some sort of handling of that special case. The map could be wrapped in a struct that defines its own `String` method before being passed to `fmt.Sprintf`, for instance. We'd lose the deterministic key order that way, but given that logging panics for this case at the moment I don't think anyone would miss it.
- Do the same check, but provide a clearer error message on panic. To me, something like "%v is not implemented in tinygo for maps" is clearer than an "unimplemented: call reflect.MapRange" error.
- Don't do the check in code, but add a note in the docs
- Don't do anything. Eventually someone will find this issue and that might be context enough. I imagine that `reflect.MapRange` would probably end up being implemented in tinygo at some point, which would obviate this issue entirely.

I'm happy to submit PRs for any of these solutions, or others if there's something else we'd want to do here. Thanks for all the work on this SDK, it's really fun to work with!

**Comment by mathetake** [comment]
Thanks for the through description! 

> Don't do the check in code, but add a note in the docs

Let's do this since as you said this is not an issue of this SDK, and the work on reflection in under progress https://github.com/tinygo-org/tinygo/pull/2640 and special casing this and handling errors are not worth it as users in any way can detect this by tests.

**Comment by while1malloc0** [comment]
Thanks for the quick reply! I added a PR above to note the caveats here.
