### ISSUE TITLE
OnPluginStartStatusFailed has no effect / plugin continues to start and service is available

### ISSUE THREAD

**Issue by JohnniDi** [tetratelabs/proxy-wasm-go-sdk#360]
## Describe the bug / error
Returning OnPluginStartStatusFailed in OnPluginStart will not fail the start up sequence.
Envoy is available with bad configuration afterwards.

## What is your Envoy/Istio version?
envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL

## What is the SDK version?
github.com/tetratelabs/proxy-wasm-go-sdk v0.21.0

## What is your TinyGo version?
tinygo version 0.26.0 linux/amd64 (using go version go1.19.2 and LLVM version 14.0.0)

## URL or snippet of your code including Envoy configuration
```
func (ctx *pluginContext) OnPluginStart(pluginConfigurationSize int) types.OnPluginStartStatus {
	// read the config
	return types.OnPluginStartStatusFailed
}
```

**Comment by mathetake** [comment]
That is not the issue of this SDK, and your configuration issue of Envoy. See `fail_open` in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto#extensions-wasm-v3-pluginconfig.

**Comment by JohnniDi** [comment]
fail_open is not set, so according to the documentation it should be false by default and resulting either in envoy not starting or request being answered with 503. both would be ok for me but does not happen.

**Comment by KTDE** [comment]
@JohniDi
I also see same issue with or without `fail_open` flag set the plugin keeps processing even `types.OnPluginStartStatusFailed `. Is this know issue from Envoy? What was the solution to that?
