### ISSUE TITLE
OnHttpRequestBody use  DispatchHttpCall, envoy send Two requests

### ISSUE THREAD

**Issue by zjb1994** [tetratelabs/proxy-wasm-go-sdk#362]
## Describe the bug / error
use DispatchHttpCall on OnHttpRequestBody, envoy send Two requests to upstream
## What is your Envoy/Istio version?
envoy v1.21.1
## What is the SDK version?
proxy-wasm-go-sdk@v0.16.1
## What is your TinyGo version?
tinygo_0.22.0_amd64
## URL or snippet of your code including Envoy configuration
```
func (l *LiveDifferentPlaces) OnHttpRequestBody(bodySize int, endOfStream bool) (int, types.Action) {

	if !endOfStream {
		return bodySize, types.ActionPause
	}

	if l.cluster != l.config.Zone {
		proxywasm.LogDebugf("LiveDifferentPlaces on body cluster:%v, zone:%v", l.cluster, l.config.Zone)
		body, _ := proxywasm.GetHttpRequestBody(0, bodySize)
		if _, err := proxywasm.DispatchHttpCall(l.cluster, l.requestHeader, body, l.requestTrailer, 50000, l.httpCallResponseCallback); err != nil {
			return bodySize, types.ActionContinue
		}
		return bodySize, types.ActionPause
	}

	return bodySize, types.ActionContinue
}

func (l *LiveDifferentPlaces) httpCallResponseCallback(numHeaders, bodySize, numTrailers int) {
	hs, err := proxywasm.GetHttpCallResponseHeaders()
	if err != nil {
		return
	}

	b, err := proxywasm.GetHttpCallResponseBody(0, bodySize)
	if err != nil {
		proxywasm.LogErrorf("LiveDifferentPlaces httpCallResponseCallback failed to get response body: %v", err)
		proxywasm.ResumeHttpRequest()
		return
	}
	proxywasm.LogDebugf("LiveDifferentPlaces httpCallResponseCallback,ResponseBody = %v", string(b))
	if l.action == types.ActionContinue {
		proxywasm.LogWarnf("LiveDifferentPlaces httpCallResponseCallback, l.action = types.ActionContinue")
		return
	}

	err = proxywasm.SendHttpResponse(200, hs, b, -1)
	if err != nil {
		proxywasm.LogErrorf("LiveDifferentPlaces httpCallResponseCallback SendHttpResponse err: %s", err.Error())
		proxywasm.ResumeHttpResponse()
	}
}
```

**Comment by mathetake** [comment]
we cannot debug it without more information (etc. envoy.yaml) plus the steps to reproduce.

**Comment by zjb1994** [comment]
I called DispatchHttpCall in OnHttpRequestBody, and then returned ActionPause, but the request went upstream twice

**Comment by mathetake** [comment]
`DispatchHttpCall` is called twice, or `DispatchHttpCall` is called once and also `return bodySize, types.ActionContinue` is reached?

**Comment by mathetake** [comment]
you should be able to identify it by inserting fmt.Println logs

**Comment by mathetake** [comment]
also: are you really sure that callsite of *your* `OnHttpRequestBody` doesn't return `Continue` in the case of dispatch?

**Comment by mathetake** [comment]
I'm closing this until you gave us the entire repro.

**Comment by zjb1994** [comment]
I have two clusters, a and b, and the default request is to cluster a. I want to forward the request to cluster b in OnHttpRequestBody. I call DispatchHttpCall after EndOfStream=true in OnHttpRequestBody, and then I return types. ActionPause, but it seems that the request has not been aborted. Clusters a and b have received the request respectively
