### ISSUE TITLE
Callback with sending HTTP response doesn't work in dispatch HTTP call with HTTP request body

### ISSUE THREAD

**Issue by blaisewang** [tetratelabs/proxy-wasm-go-sdk#367]
## Describe the bug / error

Hi all,

I have written a plugin based on the `http_auth_random` and `http_body` examples provided by the project. This plugin mainly implements the following functionality: when `endOfStream` is true, it sends the HTTP Request Header and HTTP Request Body (if it exists) to the detector cluster. Based on the instructions returned by the detector cluster, it returns the intercepted response to downstream in the callback function via the `SendHttpResponse` method.

Since the instructions returned by the detector cluster are always forbidden which is `x-filter-result=?` in the HTTP Response Header, I expect the downstream always receive an access forbidden message. The behavior is normal when only the HTTP request header is present, but when a slightly larger HTTP request body (~160KB) is present, there is a certain probability that the request will not be rejected.

Another problem is that I want to send the HTTP request header together with the HTTP request body to the detector cluster and not send any data upstream until the instructions are received. But if the `types.ActionPause` is returned at the end of `OnHttpRequestHeaders` (replace `types.ActionContinue` with `types.ActionPause` at https://github.com/blaisewang/proxy-wasm-go-sdk/blob/main/examples/dispatch_request_body/main.go#L69), it seems that the `OnHttpRequestBody` method will not be called and the whole request processing will be paused. I'm not sure if there is something wrong with my understanding or if my expectations are unattainable.

## What is your Envoy/Istio version?

Envoy v1.25.1

## What is the SDK version?

v0.21.0

## What is your TinyGo version?

v0.27.0

## URL or snippet of your code including Envoy configuration

https://github.com/blaisewang/proxy-wasm-go-sdk/tree/main/examples/dispatch_request_body

## Additional context (Optional)

Example test result:

```shell
# curl http://127.0.0.1:18000
access forbidden%
# curl http://127.0.0.1:18000
access forbidden%
# curl http://127.0.0.1:18000
access forbidden%
# curl http://127.0.0.1:18000
access forbidden%
# curl http://127.0.0.1:18000
access forbidden%
# curl http://127.0.0.1:18000
access forbidden%
# curl http://127.0.0.1:18000
access forbidden%
# curl -X POST -d "@example.txt" http://127.0.0.1:18000
passed to the real service
# curl -X POST -d "@example.txt" http://127.0.0.1:18000
passed to the real service
# curl -X POST -d "@example.txt" http://127.0.0.1:18000
passed to the real service
# curl -X POST -d "@example.txt" http://127.0.0.1:18000
access forbidden%
# curl -X POST -d "@example.txt" http://127.0.0.1:18000
access forbidden%
# curl -X POST -d "@example.txt" http://127.0.0.1:18000
passed to the real service
```

**Comment by mathetake** [comment]
The same reason as in https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/363#issuecomment-1461548912, this is not supposed to work and not specific to this SDK, but rather a limitation of Proxy-Wasm in general.
