### ISSUE TITLE
If I can add some dimensions in defining metrics?

### ISSUE THREAD

**Issue by DomineCore** [tetratelabs/proxy-wasm-go-sdk#374]
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/50765823/232375978-4bfdd5f2-0662-4e85-9e65-2a4eb99d325d.png">
I want to expose a GRPC duration metric and set a path as a dimension, how should i do?

**Comment by mathetake** [comment]
See https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/examples/metrics/envoy.yaml#L3-L5 Please make sure you check the examples raising issues.
