### ISSUE TITLE
Memory not released

### ISSUE THREAD

**Issue by 125793014** [tetratelabs/proxy-wasm-go-sdk#375]
## Describe the bug / error
Memory not released
## What is your Envoy/Istio version?
version1.16
## What is the SDK version?
proxy-wasm-go-sdk v0.22.0
## What is your TinyGo version?
tinygo version 0.26.0 linux/amd64 
## Additional context (Optional)

// Override types.DefaultHttpContext.

Execute inside container, wasm memory not released, keeps increasing

```
func (ctx *httpHeaders) OnHttpRequestHeaders(numHeaders int, endOfStream bool) types.Action {
	if tmp, _ := proxywasm.GetHttpRequestHeader("test"); tmp == "" {
		proxywasm.AddHttpRequestHeader("test", "hello")
	}

	return types.ActionContinue
}
```

**Comment by mathetake** [comment]
Please see the existing issue before raising issues. https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/349#issuecomment-1427408903
