### ISSUE TITLE
I can't correct decode tcp downstream data by using example code

### ISSUE THREAD

**Issue by Peihu2020** [tetratelabs/proxy-wasm-go-sdk#379]
## Describe the bug / error
I can't correct decode tcp downstream data by using example code. I am using envoy to tcp proxy fro my postgres server, but I can't get correct downstream data.
![image](https://user-images.githubusercontent.com/76604453/235044332-13e8b422-5eeb-43a0-ac6c-bc71da527687.png)

example code: 
![image](https://user-images.githubusercontent.com/76604453/235044463-deccdfaf-8a75-44cf-b27a-44f85a53c47e.png)

I copy code from link : https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/examples/network/main.go

## What is your Envoy/Istio version?
1.14.3
## What is the SDK version?
The latest main branch
## What is your TinyGo version?
0.27.0
## URL or snippet of your code including Envoy configuration
![image](https://user-images.githubusercontent.com/76604453/235044776-2f92b2a7-34fa-419f-97a0-8cde28012570.png)

## Additional context (Optional)
my postgres-client request information: 
![image](https://user-images.githubusercontent.com/76604453/235045350-2e1a634f-ceb8-46eb-82b3-c651ba0ec7e4.png)

I hope downstream data can decode my psql command, I don't whether this is correct requirements or not.

**Comment by mathetake** [comment]
OnDownStreamData is called for whatever tcp data is available rather than the entire body. Please check the API doc beforehand and you might want to see https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/examples/http_body for how to get the entire body.
