### ISSUE TITLE
OnDownStreamData is called for whatever tcp data is available rather than the entire body. Please check the API doc beforehand and you might want to see https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/examples/http_body for how to get the entire body.

### ISSUE THREAD

**Issue by Peihu2020** [tetratelabs/proxy-wasm-go-sdk#380]
OnDownStreamData is called for whatever tcp data is available rather than the entire body. Please check the API doc beforehand and you might want to see https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/examples/http_body for how to get the entire body.

_Originally posted by @mathetake in https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/379#issuecomment-1526949671_

**Comment by Peihu2020** [comment]
Hi Takeshi, 

I haven't answered your feedback in time because I am on vacation in the past few days. Sorry, for late answer.

My question is I can't decode my request is because I am doing tcp proxy(postgresql database proxy) rather than http request. So, I believe I can't get http request body or header and I shouldn't follow up the http_body examples as well. Please correct me if my understanding is wrong.
Peihu

**Comment by mathetake** [comment]
Hey please do not spam us creating the issue title like this from next time, and your understanding is correct.
