### ISSUE TITLE
OnTick is called multiple times every tick period

### ISSUE THREAD

**Issue by adiprerepa** [tetratelabs/proxy-wasm-go-sdk#382]
### Describe the bug / error
Maybe this is a feature, not a bug, but why does `OnTick` result in multiple OnTick calls? An example can be seen here: https://github.com/tetratelabs/proxy-wasm-go-sdk/tree/main/examples/dispatch_call_on_tick.

Digging into it, `NewPluginContext` and `OnPluginStart` are called multiple times, which (I think) are creating multiple PluginContexts which leads to the issue. Why does this happen? I would expect `OnTick` to be called **once** every period.

cc @mathetake

**Comment by mathetake** [comment]
Because it's created per worker thread. Please read the doc before raising question.

**Comment by mathetake** [comment]
Note that this is not this SDK specific
