### ISSUE TITLE
Is it possible to set any filter state?

### ISSUE THREAD

**Issue by gitanuj** [tetratelabs/proxy-wasm-go-sdk#391]
I'm writing a custom L4 filter for Envoy using this sdk, however I'm not able to set filter state `envoy.tcp_proxy.cluster` to dynamically select upstream cluster when chaining with tcp_proxy filter. From [envoy source](https://github.com/envoyproxy/envoy/blob/82ebc856ee472dec15a24b3ca3e84fdd6844a7b2/source/extensions/common/wasm/context.cc#L1102) it looks like when using `setProperty` it always prefixes the key with `wasm.`. 

Is there a way to set custom filter_state?

**Comment by mathetake** [comment]
no it's not possible due to envoy impl.
