### ISSUE TITLE
Create a documented helper functions over property/attribute API

### ISSUE THREAD

**Issue by boeboe** [tetratelabs/proxy-wasm-go-sdk#396]
As discussed internally, a better Property API would avoid needless `[]byte` parsing issues and improve the user experience of the SDK overall.

A suggestion as been implemented at my personal gihub repo here:
- https://github.com/boeboe/envoy-wasm-plugins/tree/main/print-properties

Some remarks:
 - Separate sub-package to attribute/property retrieval
 - GoLang typed getters for all available attributes/properties
 - Internal deserializers (the hardest part) and typed getPropertyXYZ functions
 - Documentation to improve UX

**Comment by boeboe** [comment]
[ingress_config_dump-2023.09.25-11.50.14.txt](https://github.com/tetratelabs/proxy-wasm-go-sdk/files/12725468/ingress_config_dump-2023.09.25-11.50.14.txt)
[ingress_logs-2023.09.25-13.17.56.txt](https://github.com/tetratelabs/proxy-wasm-go-sdk/files/12725470/ingress_logs-2023.09.25-13.17.56.txt)

**Comment by mathetake** [comment]
Just opened the initial PR which creates a new package: https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/399 

It only implements the connection-related properties, but I guess it shows how you @boeboe (or others who want to contribute) can proceed to add other properties, especially how to write unit tests over it. 

I won't work on the rest, so hand it over to anybody want to continue the work

**Comment by boeboe** [comment]
Ack, working on it now
