### ISSUE TITLE
[Question]Same vm_id with different code

### ISSUE THREAD

**Issue by caibirdme** [tetratelabs/proxy-wasm-go-sdk#397]
I see from the OVERVIEW, we could reuse a vm in each Thread to save resources. I want to know what will happen if two different wasm code apply the same vm_id( which means they have their own RootContext implementation?)

**Comment by mathetake** [comment]
assuming what you mean by `wasm code` is a Wasm binary, then envoy creates an entirely different VM, not sharing the VM.
