### ISSUE TITLE
http post call using tinygo

### ISSUE THREAD

**Issue by satz-76** [tetratelabs/proxy-wasm-go-sdk#398]
In tinygo i see net/http is not supported. I need to post to external cluster with few parameters to get token. 

My call will look like https://some.api.com/endpoint?client_id=abc&redirect_url=http://localhost:8080...

Appreciate any help here.

**Comment by mathetake** [comment]
Please refer to the examples before posting questions https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/examples/http_auth_random/main.go

**Comment by satz-76** [comment]
Sorry i should have been more clear. 
I did explore dispatchhttpcall(works for 'GET' not for 'POST'). 
May be something wrong with the way i am passing parameters to body. This is how my code looks,

`cluster := "some.api.com" --> have already defined with tls in envoy
headers := [][2]string{
  {":scheme","https"},
  {":method", "POST"},
 {":path","/endpoint"},
{":authority","some.api.com"},
 {"Content-Type","x-www-form-urlencoded"},
}

body := "client_id=abc&redirect_url=http://localhost:8080"
bodyByte := []byte(body)

data,err := proxywasm.DispatchHttpCall (
  cluster,
  headers,
 bodyByte,
 nil,
 1000,
 func(numHeaders int, bodysize int, numTrailers int){
  resp, _ := proxywasm.GetHttpCallResponseBody(0,10000)
  r := string(resp)
  proxywas.LogCriticalf("response %v",r)
 proxywasm.ResumeHttpRequest()
}
)

`

I could see in log error 400 with POST call
`
':scheme', 'https'
':method','POST'
':path','/endpoint
':authority','some.api.com'
'Content-Type','x-www-form-urlencoded',
'

with upstream response headers:
':status', '400'

This POST call works for in postman, curl, go. My guess is something i am messing when passing query parameters via dispatchhttpcall.

Appreciate any pointers.
