### ISSUE TITLE
Convert examples to use docker compose?

### ISSUE THREAD

**Issue by petedmarsh** [tetratelabs/proxy-wasm-go-sdk#406]
I wondered if there was any appetite to convert the examples to use containers/docker compose (like https://github.com/proxy-wasm/proxy-wasm-rust-sdk/tree/master/examples/hello_world)?

I personally find that workflow better than having an envoy binary installed on my dev machines.

If there is then I have some time to work on this, I thought I'd check first before diving in.

**Comment by mathetake** [comment]
Sorry, we don't have any intention to do that.
