### ISSUE TITLE
When customizing Prometheus metrics, it is essential to know how to define labels in the code. Labels play a crucial role in providing additional information and context to the metrics being collected.

### ISSUE THREAD

**Issue by zshmmm** [tetratelabs/proxy-wasm-go-sdk#407]

**Comment by jcchavezs** [comment]
Not sure what the question is but does this help? https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/examples/metrics/main.go#L69-L72

**Comment by mathetake** [comment]
answered above ^ and please follow the issue template next time.

**Comment by zshmmm** [comment]
> answered above ^ and please follow the issue template next time.

This solution uses string concatenation and then completes it through envoy filter's stats_config. In the case of a large number of tags, this approach is not user-friendly. Moreover, if the values of the tags contain special characters such as (.: /), this method cannot handle them because they will be converted to _.

**Comment by mathetake** [comment]
This is not the specific issue of SDK, but the general implementation of Envoy, not limited to Wasm at all. Please refer to the envoy community slack.
