### ISSUE TITLE
OnHttpRequestBody is not called when calling a `direct_response` route

### ISSUE THREAD

**Issue by petedmarsh** [tetratelabs/proxy-wasm-go-sdk#408]
## Describe the bug / error

When using a WASM filter on a route that returns a `direct_response` the ÒnHttpRequestBody` callback is not executed.

## What is your Envoy/Istio version?

Envoy 1.28

## What is the SDK version?

0.22.0

## What is your TinyGo version?

tinygo version 0.30.0 darwin/amd64 (using go version go1.21.3 and LLVM version 16.0.1)

## URL or snippet of your code including Envoy configuration

https://github.com/tetratelabs/proxy-wasm-go-sdk/compare/main...petedmarsh:proxy-wasm-go-sdk:http_body_direct_response?expand=1

## Additional context (Optional)

This seems to be a bug, but if it is expected behaviour then I was unable to find any documentation about it (this could well be my own fault though!)

**Comment by jcchavezs** [comment]
AFAIR direct response is actually a filter and hence it avoids the filterchain (hence any other filter). We faced something like that (I think context can be found in https://github.com/corazawaf/coraza-proxy-wasm/pull/172) so I am not sure this is a bug.

**Comment by petedmarsh** [comment]
Ah! Ok, then is there somewhere we can document this behaviour? Thankfully for me it's not something that I actually need but it did make me very confused when I was extending one of the examples which use direct_response

**Comment by mathetake** [comment]
not the issue/bug/documentation matter of this SDK, but it's an expected behavior of Envoy, so closing.

**Comment by petedmarsh** [comment]
@mathetake I'm not quite sure why this is expected behaviour as `OnHttpRequestHeaders` is called and this is using a direct response route action rather than a direct response network filter:

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-directresponseaction
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/direct_response_filter

It would make more sense to me if `OnHttpRequestHeaders` was not called too.

**Comment by mathetake** [comment]
As I said this is the known behavior of Envoy, nothing to do with SDK.
