### ISSUE TITLE
Enhancing the usability of custom metric tags in the Istio environment for WASM.

### ISSUE THREAD

**Issue by zshmmm** [tetratelabs/proxy-wasm-go-sdk#409]
## Describe the bug / error
In an Istio environment, custom metric tags can be automatically configured using extraStatTags. The default stats_config format is label=.=value;.;. It is necessary to enhance the ease of use of custom metric tags in Istio environment for WASM.

**Comment by mathetake** [comment]
Please keep in mind this is the repository for the Go SDK, and I don't think your description is not actionable here.

**Comment by zshmmm** [comment]
Istio provides some default stats_tags in stats_config, such as:
{
"tag_name": "reporter",
"regex": "(reporter=\\.=(.*?);\\.;)"
},
{
"tag_name": "source_namespace",
"regex": "(source_namespace=\\.=(.*?);\\.;)"
},
{
"tag_name": "source_workload",
"regex": "(source_workload=\\.=(.*?);\\.;)"
}

In this way, we can provide a function to automatically organize metrics in the corresponding format, which improves usability in the Istio environment without the need to write a xDS code snippet.
