### ISSUE TITLE
Is it possible to build a filter that get the body content and save as header per request?

### ISSUE THREAD

**Issue by leandrocurioso** [tetratelabs/proxy-wasm-go-sdk#415]
Please if anyone know tell me!

**Comment by jcchavezs** [comment]
You can read the request body and save it as a response header.

**Comment by leandrocurioso** [comment]
I need to direct a request (match) based on body content. Example: If client id ends with 0 or 1 or 2 etc. (regex) the route must be forwarded to a configured cluster. This cluster can be queried maybe in some form of metadata. 

My idea was to read the body field (client id) and add in request header (in the hope) I could match the client id as header since I did not found anything about matching body content.

**Comment by jcchavezs** [comment]
I don't think that is possible. By the time you access request body the headers have been already sent to upstream and hence routing has been decided.

**Comment by leandrocurioso** [comment]
You are right! I decided to go with a filter in Lua and it was totally possible! Thanks for your time =]
