### ISSUE TITLE
new release of the repo 

### ISSUE THREAD

**Issue by harsha-konda** [tetratelabs/proxy-wasm-go-sdk#427]
## Describe the bug / error

Hello Takeshi, 
Could you please create a new release of the repo as I would like to leverage some of the features that were released this year. 
The current version is almost 1 year old. 
## What is the SDK version?
v.0.2.1

**Comment by mathetake** [comment]
fair enough. thank you for the heads up! @harsha-konda

**Comment by mathetake** [comment]
https://github.com/tetratelabs/proxy-wasm-go-sdk/releases/tag/v0.23.0 here you go
