### ISSUE TITLE
wasm-plugin does not work except 'istio-proxy' namepsace

### ISSUE THREAD

**Issue by ydkmm** [tetratelabs/proxy-wasm-go-sdk#429]
## Describe the bug / error
the wasm-plugin does not work except 'istio-proxy' namepsace.
the wasmplugin aim to add a header in http header. when i kubectl this wasm-plugin into istio-proxy  namespace, the header was added and the request was matched by virtualserivce into subset v2. but once deployed into other namespace for example mm-tmp, the header was added but can not be  matched by virtual service
## What is your Envoy/Istio version?
client version: 1.16.3
control plane version: 1.16.3
data plane version: 1.16.3 (38 proxies)
## What is your TinyGo version?
tinygo version 0.30.0 windows/amd64 (using go version go1.20.7 and LLVM version 16.0.1)
## Additional context (Optional)
i use centos to curl the  servcie
![centos](https://github.com/tetratelabs/proxy-wasm-go-sdk/assets/43677576/44549b40-5bbf-4d70-9cb6-0cf2debadbe2)
![curl](https://github.com/tetratelabs/proxy-wasm-go-sdk/assets/43677576/9a3b7078-2bdb-4126-89dc-36dbec759024)
![destinationrule](https://github.com/tetratelabs/proxy-wasm-go-sdk/assets/43677576/6497e0ae-f1f4-42eb-b92e-f598c80188f5)
![httpbinv1](https://github.com/tetratelabs/proxy-wasm-go-sdk/assets/43677576/4afa9cd2-a515-40a0-aa36-c74687a243ad)
![httpbinv2](https://github.com/tetratelabs/proxy-wasm-go-sdk/assets/43677576/686763ab-2ab4-4477-856e-d6aac4677078)
![virtualservice](https://github.com/tetratelabs/proxy-wasm-go-sdk/assets/43677576/61ad47cb-650a-46ce-a493-c0dd919de14f)
![wasm-plugin](https://github.com/tetratelabs/proxy-wasm-go-sdk/assets/43677576/e2a69866-f446-4f70-88bb-dcc7dde82f88)

**Comment by ydkmm** [comment]
![image](https://github.com/tetratelabs/proxy-wasm-go-sdk/assets/43677576/093768ef-e865-4028-9c1a-ac449c10710b)
when the wasm-plugin was deployed into mm-tmp namesapce, the header was added,but the request cannot be matched by virtualserice into subset v2

**Comment by mathetake** [comment]
the question is nothing to do with SDK. maybe ask in the Istio slack?
