### ISSUE TITLE
readme example build error

### ISSUE THREAD

**Issue by szuecs** [tetratelabs/proxy-wasm-go-sdk#430]
https://github.com/tetratelabs/proxy-wasm-go-sdk?tab=readme-ov-file#build-and-run-examples does not work.
Makefile targets seem to have changed.

**Comment by mathetake** [comment]
I would appreciate it if you could fix it ;)

**Comment by mathetake** [comment]
I don't think it's not working in fact it's working on each commit on GHA. Maybe you could check the dependency? Without you giving the detail, there's nothing we can do here :)
