### ISSUE TITLE
Redis connection 

### ISSUE THREAD

**Issue by Tharsanan1** [tetratelabs/proxy-wasm-go-sdk#433]
Is it possible to connect to redis using go proxy wasm go SDK? If so, could you please provide some example for that? 

When I tried to use the go-redis code, in the compilation stage I got this error

```
/usr/local/lib/tinygo/src/net/ip.go:307:34: cannot convert p4 (variable of type IP) to type [4]byte: conversion of slices to arrays requires go1.20 or later
/usr/local/lib/tinygo/src/net/ip.go:309:35: cannot convert ip (variable of type IP) to type [16]byte: conversion of slices to arrays requires go1.20 or later
```

`tinygo version 0.31.2 linux/amd64 (using go version go1.19.2 and LLVM version 17.0.1)`

**Comment by mathetake** [comment]
no, it is not supported by the spec.

**Comment by Tharsanan1** [comment]
> no, it is not supported by the spec.

HI is there any other way to achieve a redis connection in proxy wasm go sdk?

**Comment by jcchavezs** [comment]
http redis API is one way, tho not sure about performance. Given that this
is in envoy although you could link in another ABI the runtime also needs
to support it hence not straight forward.

**Comment by Tharsanan1** [comment]
Thanks, I ll try that approach.
