### ISSUE TITLE
Question: proxywasm.GetHttpRequestHeaders() is returning error code = 6

### ISSUE THREAD

**Issue by swapnilaniljanorkarjanorkar-sap** [tetratelabs/proxy-wasm-go-sdk#434]
## Describe the bug / error
GetHttpRequestHeaders method is retuning is error = 6, I checked the source code but did not find any documentation and code related to error code 6.

## What is your Envoy/Istio version?
1.19.6

## What is the SDK version?
v0.22.0

## What is your TinyGo version?
golang:1.19.10-buster

## Additional context (Optional)
2024-04-10 00:58:38	
2024-04-09T16:58:38.711061Z	critical	envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1157	
wasm log istio-system.istio-tenant-id-wasm-filter: Failed to get request headers: unknown status code: 6	thread=48

**Comment by MengjiaLiang** [comment]
Where did you call `GetHttpRequestHeaders`?
I used to hit issues when was calling it in the wrong stage that is out of these two stages. 
```
// GetHttpRequestHeader is used for retrieving an HTTP request header value
// for given "key". Only available during types.HttpContext.OnHttpRequestHeaders and
// types.HttpContext.OnHttpStreamDone.
```

**Comment by mathetake** [comment]
https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/451
