### ISSUE TITLE
Question: Can DispatchHttpCall be used in OnHTTPStreamDone?

### ISSUE THREAD

**Issue by jonfriesen** [tetratelabs/proxy-wasm-go-sdk#437]
The title basically covers it. I'm trying to confirm some behavior I see locally.

Maybe a follow up question is, are out of band dispatches possible outside of Tick based calls?

Thanks!

**Comment by zerodayyy** [comment]
Hey @jonfriesen did you get it working after all?

**Comment by jonfriesen** [comment]
Hi @zerodayyy , I did not. I ended up packaging up my payloads and passing them to the plugin context which is using the Tick system to batch send on a timer.
