### ISSUE TITLE
Debug and Info logs are not shown

### ISSUE THREAD

**Issue by brunocascio** [tetratelabs/proxy-wasm-go-sdk#444]
## Describe the bug / error

When log using info level `proxywasm.LogInfof("hello!")` is not shown in console, but when using warn or error it's displayed properly. Log level of my istio is INFO already,

## What is your Envoy/Istio version?

Istio 1.20

## What is the SDK version?

0.23

## What is your TinyGo version?

0.31.2

## URL or snippet of your code including Envoy configuration

```golang
package main

import (
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
	"github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
)

type vmContext struct {
	// Embed the default VM context here,
	// so that we don't need to reimplement all the methods.
	types.DefaultVMContext
}

type loggerPluginContext struct {
	// Embed the default plugin context here,
	// so that we don't need to reimplement all the methods.
	types.DefaultPluginContext
}

type loggerHttpContext struct {
	// Embed the default http context here,
	// so that we don't need to reimplement all the methods.
	types.DefaultHttpContext
}

func main() {
	proxywasm.SetVMContext(&vmContext{})
}

// Override types.DefaultVMContext.
func (*vmContext) NewPluginContext(contextID uint32) types.PluginContext {
	return &loggerPluginContext{}
}

// Override types.DefaultPluginContext.
func (ctx *loggerPluginContext) NewHttpContext(contextID uint32) types.HttpContext {
	return &loggerHttpContext{}
}

// Override types.DefaultHttpContext.
func (ctx *loggerHttpContext) OnHttpResponseHeaders(numHeaders int, endOfStream bool) types.Action {

	proxywasm.LogInfof("not displayed")
	proxywasm.LogWarnf("displayed ok")

	return types.ActionContinue
}
```

**Comment by xcbeyond** [comment]
I encountered the same problem

**Comment by Ien001** [comment]
same problem.

for me, seems like the beheavior is not linear, some lines of logging are executed, while the others are not.

**Comment by pvmraghunandan** [comment]
Any update on this? Facing the same problem that only Warning logs are visible

**Comment by M4tteoP** [comment]
I did it a go by adding a test that prints logs: https://github.com/tetratelabs/proxy-wasm-go-sdk/compare/main...M4tteoP:proxy-wasm-go-sdk:logs_levels.
With a standalone envoy, everything seems to be working as expected:
```
▶ envoy --version
envoy  version: 816188b86a0a52095b116b107f576324082c7c02/1.30.1/Distribution/RELEASE/BoringSSL
▶ make run name=logs_levels
[...]
wasm log: It's 1718378068872354000: random value: 10160872717141755441
wasm log: OnTick called with LogInfof
wasm log: OnTick called with LogDebug
wasm log: OnTick called with LogInfo
wasm log: OnTick called with LogWarn
wasm log: OnTick called with LogError
wasm log: OnTick called with LogCritical
```
Based on [istio doc](https://istio.io/latest/docs/releases/supported-releases/#supported-envoy-versions), Envoy 1.28 is the one used in Istio 1.20:
```
▶ envoy --version
envoy  version: b5ca88acee3453c9459474b8f22215796eff4dde/1.28.0/Distribution/RELEASE/BoringSSL
▶ make run name=logs_levels
[...]
wasm log: It's 1718378193020451000: random value: 4166824581932656402
wasm log: OnTick called with LogInfof
wasm log: OnTick called with LogDebug
wasm log: OnTick called with LogInfo
wasm log: OnTick called with LogWarn
wasm log: OnTick called with LogError
wasm log: OnTick called with LogCritical
```
Are you all facing the issue in Istio 1.20 or can you reproduce it on a standalone envoy?

**Comment by pvmraghunandan** [comment]
I am having logs issue only after applying the WASM filter to the istio ingress gateway. Standalone envoy when ran as docker container worked fine with emitting info logs and debug when -l is set.

**Comment by mathetake** [comment]
I don't think this is a SDK specific issue, please ask in either Istio or Envoy slack instead.
