### ISSUE TITLE
Rebuild latest docker container

### ISSUE THREAD

**Issue by wimspaargaren** [tetratelabs/proxy-wasm-go-sdk#81]
I was wondering if it would be possible to rebuild the latest docker container for every master pipeline. Currently the newest image is [12 days old](https://hub.docker.com/r/getenvoy/extension-tinygo-builder/tags)

I also noticed a rather annoying typo in the readme:
`getenvoy/extention-tingyo-builder:wasi-dev`
Should be:
`getenvoy/extension-tingyo-builder:wasi-dev`

Might be nice to add an example of building filters using the docker file in the REAMDE as well!

**Comment by mathetake** [comment]
thanks @wimspaargaren for reporting this. I just resolved this in #82
