### ISSUE TITLE
Add support for on_{request,response}_meta_data.

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/proxy-wasm-go-sdk#91]
just like c++ SDK https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/7afb39d868a973caa6216a535c24e37fb666b6f3/proxy_wasm_api.h#L460-L462

**Comment by fzy-Line** [comment]
Is there any latest progress in this work?

**Comment by rtttech** [comment]
Need this feature too.

**Comment by rtttech** [comment]
> @sanfern this is fairly simple to implement so I intentionally deprioritize this in my list so that others can contribute. We welcome your contributions.

Need this feature too.

**Comment by mathetake** [comment]
https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/451
