### ISSUE TITLE
GetCalloutAttributesFromContext return value does not contain body

### ISSUE THREAD

**Issue by doriandekoning** [tetratelabs/proxy-wasm-go-sdk#95]
If I use GetCalloutAttributesFromContext on a callout with a body the body is not returned.

Is there a particular reason the body is not added here? If it can simply be added here I'd be happy to open a PR https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/proxytest/root.go#L250

**Comment by mathetake** [comment]
@doriandekoning Thanks for the report! This is not intentional so I would love to see your PR :smile: Thanks!

**Comment by doriandekoning** [comment]
Here you go: https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/96
